name = "buy-the-rip"
type = "javascript"
main = "src/index.ts"
compatibility_date = "2025-11-14"

[env.production]
routes = [
  { pattern = "buytherip.com", zone_name = "buytherip.com" },
  { pattern = "www.buytherip.com", zone_name = "buytherip.com" }
]

[build]
command = ""
cwd = "."
watch_paths = []

[[assets]]
directory = "."
include = ["*.html", "*.js", "*.css", "*.json", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg", "*.ico", "*.woff", "*.woff2", "*.ttf", "*.eot"]
